// Collections
export const GET_CAR_MODEL_COLLECTIONS = "GET_CAR_MODEL_COLLECTIONS";
export const GET_CAR_MODEL_COLLECTIONS_SUCCESS = "GET_CAR_MODEL_COLLECTIONS_SUCCESS";
export const GET_CAR_MODEL_COLLECTIONS_FAIL = "GET_CAR_MODEL_COLLECTIONS";
export const ADD_CAR_MODEL_COLLECTION = "ADD_CAR_MODEL_COLLECTION";
export const ADD_CAR_MODEL_COLLECTION_SUCCESS = "ADD_CAR_MODEL_COLLECTION_SUCCESS";
export const ADD_CAR_MODEL_COLLECTION_FAIL = "ADD_CAR_MODEL_COLLECTION_FAIL";
export const UPDATE_CAR_MODEL_COLLECTION = "UPDATE_CAR_MODEL_COLLECTION";
export const UPDATE_CAR_MODEL_COLLECTION_SUCCESS = "UPDATE_CAR_MODEL_COLLECTION_SUCCESS";
export const UPDATE_CAR_MODEL_COLLECTION_FAIL = "UPDATE_CAR_MODEL_COLLECTION_FAIL";
export const DELETE_CAR_MODEL_COLLECTION = "DELETE_CAR_MODEL_COLLECTION";
export const DELETE_CAR_MODEL_COLLECTION_SUCCESS = "DELETE_CAR_MODEL_COLLECTION_SUCCESS";
export const DELETE_CAR_MODEL_COLLECTION_FAIL = "DELETE_CAR_MODEL_COLLECTION_FAIL";